version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: udemy_clone
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: 'udemy_clone_db'
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    expose:
      - 1234
    volumes:
      - mysql-data:/var/lib/mysql
    mem_limit: 2g
    memswap_limit: 3g
volumes:
  mysql-data: